model:
  arch: base_arch
  relaxation: False
  fm_reg: null 
  k: 0.5 
  latent_show: True
  latent_G_show: True
  visualization: True
  encoder: 
    module1: 
      arch: dgcnn
      use_spatial_transform: False
      use_mean_global_feature: False
      use_batch_norm: False
      k: 20
      leakyrelu_slope: 0.2
      input_dim: 3
      l_hidden_local: [64, 64, 128, 256]
      local_feature_layer: 4
      global_feature_dim: 1024
      output_feature: global
    module2: 
      arch: mlp
      input_dim: 1024
      activation: leakyrelu
      leakyrelu_slope: 0.2
      out_activation: linear
      l_hidden: [512, 256]
      use_batch_norm: False
      output_dim: 2
    # module1: 
    #   arch: foldnet
    #   feat_dims: 2 
    #   k: 16
  decoder: 
    module1: 
      arch: mlp_pointcloud
      input_dim: 2
      activation: relu
      leakyrelu_slope: None
      out_activation: linear
      l_hidden: [256, 512]
      use_batch_norm: False
      output_point_dim: 3
      number_of_points: 512  
trainer: base
training:
  n_epoch: 5000
  loss:
    type: chamfer
  optimizer:
    name: 'adam'
    lr: 0.001
  lr_schedule: null
  resume: null
  augmentations: null
  print_interval: 100
  val_interval: 500
  save_interval: 500
logger:
  visualize_number: 3
  visualize_interval: 1000
  visualize_latent_space: 500
data:
  training:
    loader: superquadric
    path: datasets/interpolation_old_4
    csv_name: train_datalist.csv
    object_types: ['cone', 'cylinder', 'ellipsoid']
    input_type: full
    input_noise: False
    input_normalization: True
    use_med: True
    split: training
    batch_size: 16
    num_workers: 8
  validation:
    loader: superquadric
    path: datasets/interpolation_old_4
    csv_name: validation_datalist.csv
    object_types: ['cone', 'cylinder', 'ellipsoid']
    input_type: full
    input_noise: False
    input_normalization: True
    use_med: True
    split: validation
    batch_size: 16
    num_workers: 8
  test:
    loader: superquadric
    path: datasets/interpolation_old_4
    csv_name: test_datalist.csv
    object_types: ['cone', 'cylinder', 'ellipsoid']
    input_type: full
    input_noise: False
    input_normalization: True
    use_med: True
    split: test
    batch_size: 16
    num_workers: 8